### ISSUE TITLE
Help with a translation file

### ISSUE THREAD

**Issue by RadioactiveRadio** [nate-xyz/paleta#16]
I figured out the translation file.po and translated it to hindi but i'm not a developer and don't know how to do pull requests. Can someone help out?

**Comment by nate-xyz** [comment]
Thanks for translating! To open a PR you have to:
- fork my repo
- clone your fork
- create a new branch on your fork
- push the changes to the new branch in your fork
- open a pull request on my repo from your branch on your fork

Here's more detailed info: 
- [forking a repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo)
- [making a branch from github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository) or [making a branch with git](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)
- [creating a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)


Let me know if you have any other questions! Alternatively if you can't do any of the above or you don't want to, email me directly and I'll push it if you want, but then you don't get credit as a contributor on the github repo. (You still get credit in the app regardless)
