### ISSUE TITLE
"Open" label next to open button

### ISSUE THREAD

**Issue by gregorni** [nate-xyz/paleta#2]
There should be a label inside of the open button, simply saying "Open" to more clearly explain what the button does. Similar thing can also be with the edit button on the Palette page.

**Comment by lionblaze55** [comment]
I kind like the image in the corner, looks cleaner that way. Why does this have to change?

**Comment by gregorni** [comment]
I mean, it doesn't have ro be that way, but I thought since most GNOME apps do it like that, we should do the same. Of course, feel free to disagree in favour of a less cluttered interface.

**Comment by nate-xyz** [comment]
I personally prefer a more compact interface, and I don't think I'm violating GNOME HIG with this choice. ([see here](https://developer.gnome.org/hig/patterns/containers/header-bars.html#header-bar-buttons)) If I'm misunderstanding these guidelines or the majority of people feel labels would be good for visibility reasons, I'd be happy to add them.
