### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by gregorni** [nate-xyz/paleta#3]
Keyboard shortcuts like `Ctrl`+`O` to open, `Ctrl`+`Q` to close, and `Ctrl`+`?` to show keyboard shortcuts should be implemented.

**Comment by nate-xyz** [comment]
Good idea, I'll add that. Any other shortcut suggestions?

**Comment by gregorni** [comment]
Maybe `Ctrl`+`Enter` to start extracting palettes and`Ctrl`+`S` to save palette? I haven't got a good one for entering edit mode.

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/paleta/commit/44b346f0494bbd96db8c862d3f71f9335c623338
