### ISSUE TITLE
[Request] Have Paleta Remember Window size

### ISSUE THREAD

**Issue by Scotty-Trees** [nate-xyz/paleta#33]
I'm using the 0.3.1 version of Paleta (flatpak) on Fedora 38 Gnome. Whenever I open the application it always defaults to this size as shown below: 

![Screenshot from 2023-04-22 13-06-08](https://user-images.githubusercontent.com/45135187/233797393-419b90f2-d035-4cb4-8ff0-3f5d5a90fae1.png)

Most (if not all?) Gnome apps when you adjust it's window size, will remember that window size on the next time the application is launched. I think the current window setup is a big large and takes up too much screen space. I try to adjust the window size to something a bit more manageable as show below, but every time I reopen Paleta, it defaults to the first image I showed above:

 
![Screenshot from 2023-04-22 13-09-27](https://user-images.githubusercontent.com/45135187/233797529-b393f3f9-bb2d-4096-a6b7-4ebcedb67dd1.png)

Is it possible to add in the ability for Paleta to remember window size and/or location? I would greatly appreciate this addition to this very useful application as well. Thank you for your time and please let me know if you need any further information from me, thanks.

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/paleta/commit/9964414e3f271740739bede1e4306ccd81a55887
