### ISSUE TITLE
Add translation support

### ISSUE THREAD

**Issue by rene-coty** [nate-xyz/paleta#6]
I would be nice to be able to translate this app into several languages, this would require a .pot file with the translatable strings in the /po directory..

**Comment by Vistaus** [comment]
I agree. And if implemented, I will provide the Dutch translation. 🙂

**Comment by nate-xyz** [comment]
Added! Let me know if there are any issues.
https://github.com/nate-xyz/paleta/commit/cd3bcb0af0666ac329ed33ffcf07d9eb1634e23e

**Comment by tfuxu** [comment]
@nate-xyz You should also consider adding Paleta to a translation platform, preferably to Weblate. It's open-source and most people who are into translating open-source projects have an account here.

Here's an guide on Weblate's docs on continuous localization and how to integrate it: https://docs.weblate.org/en/latest/admin/continuous.html
