### ISSUE TITLE
Better appdata summary

### ISSUE THREAD

**Issue by bertob** [nate-xyz/paleta#7]
The current summary "Extract the dominant colors from any image." could be better, it's a bit too long and has a period at the end.

I'd recommend something like "Extract color palettes from images" or "Generate color palettes".

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/paleta/commit/26f157789052443a569dcc321a24ec5fbb2be476
